baseURL = 'https://shinonome-shizuka.github.io'
copyright = '不可商用，转载署名，标注原地址即可。</br>@Copyright 2023 Shinonome-Studio & Shinonome Shizuka'
# googleAnalytics = '326384852'
defaultContentLanguage = 'zh'
languageCode = 'zh-Hans'
theme = 'dream'
title = '闲人后院'
# disqusShortname = 'shinonome-shizuka-github-io'
hasCJKLanguage = true

[params]
accessCount = true
author = '東雲閑'
avatar = '/me/shizuka_new_bbg.png'
background = "#E3E3E3"
calloutInPost = true
description = '专注游戏、思考与文学，東雲閑的自留地。'
headerTitle = '闲人后院门不闭'
i18n = 'zh'
images = '/me/background@zetsubo.jpg'
maxTags = 5
motto = '横剑听风雨浸溪，无上清凉花满席。</br><span style="font-size:12px;color: gray;">微信公众号 @shizuka_backyard</span>'
utterancesRepo = "shinonome-shizuka/shinonome-shizuka.github.io"
# backgroundImage = "/me/background.jpg"
linkColor = "#005CFF"

rss = true

# dark mode
backgroundDark = "#14191E"
backgroundImageDark = "https://tva1.sinaimg.cn/large/006R15FXgy1h54inxaza8j32yo1nnqv6.jpg"
dark404 = true
darkLinkColor = "#005CFF"
darkNav = true
defaultDark = true

email = "shizuka@writeme.com"
facebook = "Shinonome.Shizuka"
instagram = "whitemage.null"
twitter = "Kakoii_Souryo"
# mastodon = ""
# linkedin = ""
bandcamp = "maira_yuki"
cowlevel = "Shinonomeshizuka"
github = "shinonome-shizuka"
playstation = "SrvenX-07"
steam = "shinonomeshizuka"
# xbox = "Mostima#1965"
# stackoverflow = ""
# codepen = ""

siteStartYear = 2020

favicon = "/me/favicon.ico"

highlightjs = true
# highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
highlightjsExtraLanguages = ["ocaml"]
highlightjsTheme = "gruvbox-light"
highlightjsThemeDark = "gruvbox-dark"

# search
enableSearch = true

# options
showSummaryCoverInPost = true
# hasTwitterEmbed = true
# reversePostAndAside = true
# shareInAside = true
# fixedNav = true
collapseBySummary = true
collapsibleTags = true

[params.advanced]
# customCSS = ["css/custom.css"]
# customJSBefore = []
# customJS = []

[params.experimental]
jsDate = true
jsDateFormat = "yyyy年MM月dd日"
